implement hash password
tarasulo/onlineshop pull request #8
Opened 2019-10-04 13:33 UTC by tarasulo

2019-10-06 06:31 UTC, boroda4436 requested changes

2019-10-06 06:31 UTC, boroda4436 commented on src/main/java/internet/shop/controller/LoginController.java
> +            String salt = userService.getSaltByLogin(login);
@tarasulo Чому б не використати цей метод на рівні сервісу наприклад тут: метод userService.login(...)

2019-10-07 11:41 UTC, tarasulo commented on src/main/java/internet/shop/controller/LoginController.java
> +            String salt = userService.getSaltByLogin(login);
done

2019-10-08 08:30 UTC, boroda4436 commented
@tarasulo Чому коміт по Hibernate в тебе в цій ДЗ?

2019-10-08 08:31 UTC, boroda4436 approved these changes

2019-10-08 09:34 UTC, tarasulo commented
> @tarasulo Чому коміт по Hibernate в тебе в цій ДЗ?
попередня не була прийнята, тому не мерджив і не робив новий пулреквест

2019-10-08 09:35 UTC, merged